//
//  PromptSpec.swift
//  PromptMAXX
//
//  Framework-free value types for describing a prompt before it is sent to a
//  model. The compiler deliberately renders only explicit user-authored
//  fields; it never asks a model to expose or reconstruct hidden reasoning.
//

import Foundation

nonisolated public struct PromptSpecValidationIssue: Codable, Hashable, Sendable {
    public let field: String
    public let message: String

    public init(field: String, message: String) {
        self.field = field
        self.message = message
    }
}

/// A structured, model-independent description of a prompt.
///
/// Invariants:
/// - `id` is stable for the lifetime of the spec and is never regenerated by
///   normalization.
/// - Text is trimmed and list values are de-duplicated by `normalized`.
/// - `objective` and `outputContract` are required for compilation.
/// - `missingQuestions` are intentionally informational and do not make a
///   spec invalid; callers may choose to ask them before running a prompt.
nonisolated public struct PromptSpec: Codable, Hashable, Sendable {
    public static let currentSchemaVersion = 1
    public static let untitledTitle = "Untitled Prompt"

    public let id: UUID
    public var schemaVersion: Int
    public var title: String
    public var objective: String
    public var context: String
    public var constraints: [String]
    public var assumptions: [String]
    public var missingQuestions: [String]
    public var outputContract: String
    public var acceptanceCriteria: [String]

    public init(
        id: UUID = UUID(),
        schemaVersion: Int = PromptSpec.currentSchemaVersion,
        title: String = PromptSpec.untitledTitle,
        objective: String = "",
        context: String = "",
        constraints: [String] = [],
        assumptions: [String] = [],
        missingQuestions: [String] = [],
        outputContract: String = "",
        acceptanceCriteria: [String] = []
    ) {
        self.id = id
        self.schemaVersion = schemaVersion
        self.title = title
        self.objective = objective
        self.context = context
        self.constraints = constraints
        self.assumptions = assumptions
        self.missingQuestions = missingQuestions
        self.outputContract = outputContract
        self.acceptanceCriteria = acceptanceCriteria
    }

    /// A stable, UI-ready representation with blank values removed.
    public var normalized: PromptSpec {
        PromptSpec(
            id: id,
            schemaVersion: schemaVersion,
            title: Self.normalizedText(title).isEmpty ? Self.untitledTitle : Self.normalizedText(title),
            objective: Self.normalizedText(objective),
            context: Self.normalizedText(context),
            constraints: Self.normalizedList(constraints),
            assumptions: Self.normalizedList(assumptions),
            missingQuestions: Self.normalizedList(missingQuestions),
            outputContract: Self.normalizedText(outputContract),
            acceptanceCriteria: Self.normalizedList(acceptanceCriteria)
        )
    }

    public var validationIssues: [PromptSpecValidationIssue] {
        let spec = normalized
        var issues: [PromptSpecValidationIssue] = []

        if spec.schemaVersion != Self.currentSchemaVersion {
            issues.append(.init(
                field: "schemaVersion",
                message: "Unsupported schema version \(spec.schemaVersion); expected \(Self.currentSchemaVersion)."
            ))
        }
        if spec.title.isEmpty {
            issues.append(.init(field: "title", message: "A title is required."))
        }
        if spec.objective.isEmpty {
            issues.append(.init(field: "objective", message: "An objective is required."))
        }
        if spec.outputContract.isEmpty {
            issues.append(.init(field: "outputContract", message: "An output contract is required."))
        }

        return issues
    }

    public var isValid: Bool { validationIssues.isEmpty }

    /// A deterministic display/preview rendering. Use `PromptCompiler.compile`
    /// when callers need validation to be enforced before execution.
    public var compiledPrompt: String {
        PromptCompiler.render(normalized)
    }

    private static func normalizedText(_ value: String) -> String {
        value
            .replacingOccurrences(of: "\r\n", with: "\n")
            .replacingOccurrences(of: "\r", with: "\n")
            .components(separatedBy: "\n")
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { !$0.isEmpty }
            .joined(separator: "\n")
            .trimmingCharacters(in: .whitespacesAndNewlines)
    }

    private static func normalizedList(_ values: [String]) -> [String] {
        var seen = Set<String>()
        return values
            .map(normalizedText)
            .filter { !$0.isEmpty }
            .filter { seen.insert($0).inserted }
    }
}
